server:
  port: 6083

spring:
  application:
    name: gateway-api

  zipkin:
    base-url: http://zipkin:9411

  cloud:
    gateway:
      routes:
        - id: project-api
          uri: lb://PROJECT-API
          predicates:
            - Path=/v1/projetos/**
        - id: customer-api
          uri: lb://CUSTOMER-API
          predicates:
            - Path=/v1/clientes/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/